### ISSUE TITLE
Failing to detect Microsoft.WindowsDesktop.App\6.0.0-rc.1.21451.3 when requesting 6.0

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#120]
The Microsoft.WindowsDesktop.App team is not providing a productversion.txt file so verification of installation of WindowsDesktop runtime fails verification when requesting 6.0 channel.

https://github.com/dotnet/install-scripts/issues/214#issue-997888385
https://github.com/dotnet/install-scripts/issues/215#issue-998355686

I have requested a NoVerify switch to bypass verification to work around this issue.

**Comment by SteveBush** [comment]
Commenting out adding DesktopRuntimeVersions to install in Install-DotNetSdk.ps1fixes this problem for 6.0.


```
	# Add target frameworks of the form: netXX
	$targetFrameworks |? { $_ -match 'net(\d+\.\d+)' } |% {
        $v = $Matches[1]
        $runtimeVersions += $v
    #    if (-not ($IsMacOS -or $IsLinux)) {
    #        $windowsDesktopRuntimeVersions += $v
    #    }
	}
```

**Comment by SteveBush** [comment]
Since the install script works correctly for net5.0, I have isolated the proposed fix to just the 6.0 desktop channel.

```
        if (-not ($IsMacOS -or $IsLinux -or $v -eq '6.0')) {
            $windowsDesktopRuntimeVersions += $v
        }
```

**Comment by AArnott** [comment]
Thanks for thinking this problem through so well. From the comment on your first linked issue it sounded like this is a very temporary thing. If we think the 6.0 desktop runtime problem will be solved soon, I'd rather not update the template to workaround a short-term bug.
But if the desktop runtime is going away in 6.0 because of their new model, then we may want to make a change anyway.

**Comment by SteveBush** [comment]
From my understanding, the DotNet installer scripts team is waiting on a fix from the Desktop runtime team to include productversion.txt to indicate which product got installed.  The scripts team would use the contents of this file to verify the installation directory.  The problem exists when the discovered version does not equate to the installation directory name.  

I don't have any insight on whether or not the desktop runtime will make the productversion.txt fix anytime soon.  For now, the above workaround unblocks my pipeline.  If anyone changes the global.json to build an RC version of net6.0, they will face the same problem.

**Comment by AArnott** [comment]
Thanks for sharing then. I won't merge the change right away, but we can leave the issue active to draw attention of folks looking for a workaround.
