### ISSUE TITLE
publish-deployables.yml needs windows path delimiters

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#150]
Publish-deployables.yml runs in a Windows build host.  dotnet nuget push fails to find the deployables-Windows folder due to forward slashes in the path.

`script: dotnet nuget push $(Pipeline.Workspace)/deployables-Windows/*.nupkg -s $(ci_feed) -k azdo --skip-duplicate
`

Fix is to use Windows backslash delimters:

`script: dotnet nuget push $(Pipeline.Workspace)\deployables-Windows\*.nupkg -s $(ci_feed) -k azdo --skip-duplicate
`

**Comment by AArnott** [comment]
Nice catch.

**Comment by AArnott** [comment]
The trick is that some pipelines (based on this template) run this step on linux agents, which is in fact how I made this error in the first place. A backslash would be misinterpreted on linux, so I'll fix using a pwsh cmdlet that will normalize on the right slash.

**Comment by SteveBush** [comment]
Makes sense. I changed to a Windows build host when the template changed the default to use a Windows build host.
