### ISSUE TITLE
Two copies of code coverage files are being created.

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#161]
Two copies of a code coverage file are being created with the most recent changes.  This is causing the report generator tool do double the work to dedupe the code coverage data.

 - VssAdministrator_fv-az336-857_2022-06-08_23_05_45\In\fv-az336-857\VssAdministrator_fv-az336-857_2022-06-08.23_05_16.cobertura.xml
 - fe82ccff-2b3d-45c8-a0db-a85e0bbb9970\VssAdministrator_fv-az336-857_2022-06-08.23_05_16.cobertura.xml

Proposed fix in coverageResults.ps1 to remove duplicates from */In/* folder:

`$coverageFiles = @(Get-ChildItem "$RepoRoot/test/*.cobertura.xml" -Recurse | Where {$_.FullName -notlike "*/In/*"  -and $_.FullName -notlike "*\In\*" })
`

There may be a more elegant way to do this but this unblocked me.

**Comment by AArnott** [comment]
Thanks for reporting.

> this unblocked me.

Was this actually blocking in some way? What led you to discover this in the first place? Was the added time actually significant in your build?

> remove duplicates from /In/ folder

I'd prefer to not even generate the duplicates in the first place. @MarcoRossignoli any ideas?

**Comment by MarcoRossignoli** [comment]
I think it's related to the by design behavior of trx logger with datacollector(previous will be using coverlet msbuild integration, ignored by AzDo) https://github.com/microsoft/vstest/issues/2334#issuecomment-1140330331

**Comment by SteveBush** [comment]
@MarcoRossignoli 

The proposed fix only works with there is one level of test projects (e.g $RepoRoot/test/MyTestProject/TestResults.  I have subfolders of test projects so I need to use -Recurse.  The following code worked for me.  It excludes any "In" folder on Windows and non-Windows which has the duplicate code coverage file.

@AArnott 

The report generation takes 3 seconds.  The path fixups is what is taking so long.

```
Get-ChildItem "$RepoRoot/test/*.cobertura.xml" -Recurse | Where {$_.FullName -notlike "*/In/*"  -and $_.FullName -notlike "*\In\*" }
```

**Comment by AArnott** [comment]
I'm working on the change now. Thank you so much for the feedback, @SteveBush and the proposed fix. I hope you'll take a look at the PR when it comes out.

**Comment by AArnott** [comment]
> The path fixups is what is taking so long.

Are you talking about the new regex replacements in publish-codecoverage.yml? I wonder how cutting the file count by half drops time from minutes to just 3 seconds.
