### ISSUE TITLE
Convert-PDB.ps1 has incorrect 'synopsis'

### ISSUE THREAD

**Issue by Eilon** [AArnott/Library.Template#24]
See this line:

https://github.com/AArnott/Library.Template/blob/a2556bf66ce72ef84c33077b94a9c83100d88e37/azure-pipelines/Convert-PDB.ps1#L3

It looks like this file was copied from somewhere, but I can't tell from where. It's in several places across GitHub:

https://github.com/search?utf8=✓&q=filename%3Aconvert-pdb.ps1&type=Code&ref=advsearch&l=&l=

The synopsis should be changed to a correct description of the utility. Something like, `Converts between Windows PDB and Portable PDB formats.` (text taken from https://github.com/dotnet/symreader-converter#microsoftdiasymreaderconverter).

**Comment by AArnott** [comment]
Wow. Mistakes die hard. I *think* I am the original author of this script. Interesting to see how far the script has spread. Anyway, nice catch. I'll get this fixed.

**Comment by Eilon** [comment]
Hilarious. Thanks for fixing!
