### ISSUE TITLE
Make it easier to run Expand-Template.ps1 from CMD window

### ISSUE THREAD

**Issue by Eilon** [AArnott/Library.Template#25]
Right now if you run `Expand-Template.ps1` from a CMD window you get the good old Execution Policy error message, and you have to run "cryptic" PowerShell commands to bypass the execution policy. What _some people_ do is add a CMD file that runs the PS1 file with the appropriate bypass option to avoid the error, such as the ASP.NET team's repos:

```
https://github.com/aspnet/AspNetCore/blob/master/build.cmd#L3
```

**Comment by AArnott** [comment]
You mean what I already do here?

https://github.com/AArnott/Library.Template/blob/a2556bf66ce72ef84c33077b94a9c83100d88e37/init.cmd#L2

Sure: I'll apply that to `Expand-Template.ps1` as well.

**Comment by AArnott** [comment]
Nevertheless, the link you shared was interesting as they took more care to communicate failure exit codes. Thanks for the tip.
