### ISSUE TITLE
Support for MacOS Hosted Runners on ARM64 

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#286]
Mac build runners moved from AMD64 (Intel) to ARM64 (Apple M1) CPUs, starting with macOS. I build MAUI projects, and the latest MAUI packages require the latest XCode SDK, which is only available on macOS. Azure works fine as it is still using Intel-based MacOS hosts.

The fix is to download and install the correct DotNET SDK based on the architecture of the build host.  As Azure still works, fixing this for my private builds is in my backlog. 

Virtual Machine | Processor (CPU) | Memory (RAM) | Storage (SSD) | Workflow label
-- | -- | -- | -- | --
Linux | 2 | 7 GB | 14 GB | ubuntu-latest, ubuntu-24.04 [Beta], ubuntu-22.04, ubuntu-20.04
Windows | 2 | 7 GB | 14 GB | windows-latest, windows-2022, windows-2019
macOS | 3 | 14 GB | 14 GB | macos-12
macOS | 4 | 14 GB | 14 GB | macos-13
macOS | 3 (M1) | 7 GB | 14 GB | macos-latest or macos-14

**Comment by AArnott** [comment]
You say Azure still works. I assume that's Azure Pipelines. So where does it fail? 

> Mac build runners moved ..., starting with macOS

Aren't _all_ mac build runners running macOS by definition?

**Comment by SteveBush** [comment]
I have tracked down the issue to running out of space on the GitHub Action M1 build host during the build step.  I believe this is isolated to my pipeline, as no logs are produced due to the lack of disk space.

Azure Pipelines are using AMD64 MacOS hosts.  GitHub Actions are running ARM64 (M1) MacOS hosts.  On Azure Pipelines MacOS hosts, the AMD64 version of dotnet is installed (https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401/dotnet-sdk-8.0.401-osx-x64.tar.gz).  On GitHub Actions (macos-14), the ARM64 version of dotnet is installed (https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.401/dotnet-sdk-8.0.401-osx-arm64.tar.gz). With the build step failing (no logs due to disk space issue), I had thought the build step wasn't executing on GitHub Actions.

**Comment by AArnott** [comment]
It sounds like you're saying you filed this issue in error.

I verified that the GitHub workflows in this template not only run successfully, but on GA they install the arm64 .NET SDK as expected: https://github.com/AArnott/Library.Template/actions/runs/10669780010/job/29572410615
