### ISSUE TITLE
`PackageOutputPath` gets overriden by MSBuild for SDK Projects and packages are still produced in the project source tree

### ISSUE THREAD

**Issue by abdes** [AArnott/Library.Template#310]
`PackageOutputPath` needs to be set in Directory.build.targets or it gets overriden by MSBuild for SDK Projects and will not have the desired effect.

https://github.com/AArnott/Library.Template/blob/61efb7191c6268858565dfaab01a778091bca1e2/Directory.Build.props#L5-L8

**Comment by AArnott** [comment]
Thanks for reporting.
The title says SDP projects and the description says SDK projects. 
In my experience SDK projects take the PackageOutputPath as set here just fine, so I'm guessing you're talking about SDP projects. But I've never heard of SDP projects. What are they?

**Comment by abdes** [comment]
Typo in title corrected

**Comment by abdes** [comment]
You think it works fine because the project is at the root and bin is also at the root. Put src and the csproj in a subdirectory and you will see the problem. 

Anyway, thanks for writing the props files, really helpful.

**Comment by AArnott** [comment]
I see. Well, I'm glad you found the solution to the problem. I have one mono-repo that I (have to) work in too, so I sympathize.
Library.Template is decidedly *not* designed to support mono-repos though, and we have repos based on Library.Template that build on or modify PackageOutputPath within project evaluation so moving the definition to .targets would probably break folks, in favor of making 'mono repos' work with fewer changes, which IMO is putting priorities backwards.

Best of luck on your mono-repo though.

**Comment by abdes** [comment]
> Best of luck on your mono-repo though.

It's working well actually, I struggled a lot at the beginning, but thanks to good ideas from many other projects, including yours, I now have a working setup that saves me a lot of time. Take a look if you want to get inspired for your future monrepo and feel free to submit issues if you see horrible things 😄
