### ISSUE TITLE
Choco install should automatically confirm

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#47]
In azure-pipelines\install-dependencies.yml, the choco install command should automatically confirm prompts.  Users may not have set global confirmation to true.

File: azure-pipelines\install-dependencies.yml
Fix: choco install procdump -y

**Comment by AArnott** [comment]
Is this really needed? Don't Azure Pipelines agents *guarantee* that choco has been preconfigured for global confirmation? I've never had an agent hang on a user prompt. Have you?

**Comment by SteveBush** [comment]
Hosted azure pipelines do guarantee choco clients are preconfigured for global confirmation.  However, a local windows agent doesn't necessarily have this guarantee.  In my situation, I use a local Windows agent to debug my pipelines.  I can view the work folder locally and verify my Azure pipeline is producing what I expect.  On my developer machine (local agent), I don't have a global confirmation setting.

**Comment by AArnott** [comment]
Got it. Thanks.
