### ISSUE TITLE
Install-DotNet script out of date

### ISSUE THREAD

**Issue by jepetty** [AArnott/Library.Template#74]
I don't know what happened, but it just bit us today that the install URI `https://dotnetcli.blob.core.windows.net/dotnet/$sdkOrRuntime/$Version/dotnet-$($sdkOrRuntime.ToLowerInvariant())-$Version-win-x64.exe` no longer exists (i.e. `https://dotnetcli.blob.core.windows.net/dotnet/sdk/3.1.402/dotnet-sdk-3.1.402-win-x64.exe` returns 404). 

I'm updating us to use https://dot.net/v1/dotnet-install.ps1, but you may want to update your template as well :)

**Comment by AArnott** [comment]
We use that script too:

https://github.com/AArnott/Library.Template/blob/41d2e5533ffdacbb6abf9555860bead64cbcd1ea/tools/Install-DotNetSdk.ps1#L140

We have a *lot* of repos that use this script and yours is the only failure I've heard. I just queued [another build of this repo](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=3610&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=73c4289c-110b-5085-4a98-4009fa5cc9c8) and it succeeds. So I wonder if the repo where you saw the failure had an outdated version of the script that we already had a fix for in this repo. Wanna try copying the latest from this repo into yours to see if it works for you?

**Comment by jepetty** [comment]
You were right, thanks. I don't know what update allowed my build to avoid [this line](https://github.com/AArnott/Library.Template/blob/master/tools/Install-DotNetSdk.ps1#L72) but updating it did resolve my problem. Closing as not a bug. Thanks for your help!

**Comment by jepetty** [comment]
FYI this actually wasn't resolved for us in _all_ cases by switching to the updated version of the script (see [bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1229288)). It looks like this only affects repositories that set the DOTNET_ROOT (possibly by not using the UseDotNet task, though I haven't verified that it works in those pipelines)
