### ISSUE TITLE
Set-Env and add-path commands are deprecated in GitHub Actions

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#79]
GitHub due to a vulnerability has moved to using Environment files: $GITHUB_ENV instead of STDOUT.

The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files.

[Environment Files on Github](https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files)

Similar problem for add-path.

**Comment by AArnott** [comment]
Thanks. This is very odd because this was tracked by https://github.com/dotnet/Nerdbank.GitVersioning/pull/516 and the fix for it is already in place in this repo. I'll have to dig deeper I guess.

**Comment by AArnott** [comment]
Oh! This has nothing to do with that NB.GV bug. It's just the scripts in this repo itself that are calling `::set-env`

**Comment by SteveBush** [comment]
Yes.  And I think one instance of ::set-path.

Sent from my iPad

On Nov 16, 2020, at 8:43 AM, Andrew Arnott <notifications@github.com> wrote:

﻿

Oh! This has nothing to do with that NB.GV bug. It's just the scripts in this repo itself that are calling ::set-env
